= Pratique intermédiaire du shell Linux (1/2)
:hp-tags: linux shell

== _Présentation de l'activité_ 

=== Objectifs

À l'issue de ce TP, vous devez être capable de ... :

* mettre en pratique les différents mécanismes liés aux méta-caractères du shell (jokers, redirection, tubes, enchaînement de commandes...)

* visualiser/contrôler/tuer les processus du système

=== Durée

4h

=== Compte rendu

* Réponses aux question posées. Vous apporterez une attention particulière à la rédaction et à l'orthographe.
* Retranscrire toutes les commandes.

=== Pré-requis

* Notions de base sur les systèmes d'exploitation.
* Maîtrise des commandes de base du shell Linux (TP précédent)

=== Ressources 

.Matériels :

* PC Linux avec distribution OpenSUSE

.Logiciels :

* Néant

.Documents :

* Pages de manuel Linux

== _Travail demandé_

:numbered:

[IMPORTANT]
=====
Dans la mesure du possible, il est demandé de saisir les commandes présentées dans les exemples afin de constater par vous même leur résultat et de mieux comprendre leur rôle.
=====

== Méta-caractères du shell

Des *méta-caractères* sont des caractères qui remplacent/décrivent d'autres caractères ou qui prennent un sens particulier dans un certain contexte. 

Dans le cadre du shell, ces méta-caractères sont généralement utilisés :

* pour constituer des motifs qui désignent un ensemble de fichiers/répertoires

* pour agir sur le comportement des commandes.

[source]
.Exemple :
-----
$ ls /dev/tty* <1>
-----

<1> Cette commande liste tous les fichiers du répertoire `/dev` dont le nom débute par *tty*.

Parmi les méta-caractères les plus répandus, on trouve : 

* l'astérisque '`*`',
* le point d'interrogation '`?`'
* le point d'exclamation '`!`'
* les crochets '`[]`'
* les signes '`<`' et '`>`'
* la barre verticale '`|`'
* l'esperluette '`&`'
* le point virgule '`;`'
* l'antislash '`\`'

Ainsi, lorsqu'ils apparaissent dans des commandes, le shell leur accorde une signification particulière et les traite avant d'exécuter la commande.

Des moyens existent cependant pour annuler le sens particulier des méta-caractères au sein des commandes :

* L'**échappement** qui annule le sens particulier de *TOUS* les méta-caractères.
+
Il consiste à précéder le méta-caractère par un antislash ('`\`'). Pour annuler le sens particulier de l'antislash, il suffit de le doubler.
+
.Exemple : Affichage d'un texte comportant un antislash avec la commande *echo*
-----
$ echo Windows7 est installé par défaut dans c:\windows
Windows7 est installé par défaut dans c:windows  <1>

$ echo Windows7 est installé par défaut dans c:\\windows
Windows7 est installé par défaut dans c:\windows <2>
$
-----
<1> il manque l'antislash entre '`:`' et '`windows`' car il a été "`englouti`" par le shell qui lui accorde une signification particulière
<2> en doublant l'antislash dans la commande, l'affichage est conforme à ce qui est attendu


* les *guillemets doubles* ("...") qui annulent l'interprétation de certains méta-caractères par le shell.
+
L'utilisation des guillemets double ne désactive pas les mécanismes de *substitution de commande* et de *substitution de variables* qui seront abordés plus loin.
+
.Exemple : affichage de texte comportant les signes '`<`' et '`>`' et faisant référence à une variable d'environnement
----
$ echo le nom de ma machine est <$HOSTNAME>
bash: syntax error near unexpected token `newline' <1>
$ echo "le nom de ma machine est <$HOSTNAME>"
le nom de ma machine est <topix> <2>
$ 
----
<1> Le signe '`<`' a été interprété par le shell => il génère une erreur car la commande n'a pas de sens
<2> les guillemets double ont annulé l'interprétation des signes '`<`' et '`>`' mais pas de '`$`' en tant que préfixe de variable d'environnement => celle-ci est remplacée dans le texte par sa valeur : c'est ce qu'on appelle la *substitution de variable*

* les *guillemets simples* (pass:['] pass:[']) qui annulent le sens de la plupart des méta-caractères.
+
.Exemple : même exemple que précédemment
----
$ echo 'le nom de ma machine est <$HOSTNAME>'
le nom de ma machine est <$HOSTNAME> <1>
$ 
----
<1> ici aucun des méta-caractères utilisés n'a été interprété. Le texte est rendu tel quel.



